# Generated by Django 5.0.1 on 2024-04-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoDownloader', '0002_downloaded_res_downloaded_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaded',
            name='res',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='downloaded',
            name='url',
            field=models.URLField(),
        ),
    ]
