# Generated by Django 5.0.1 on 2024-04-02 17:48

import videoDownloader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoDownloader', '0003_alter_downloaded_res_alter_downloaded_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaded',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='downloaded',
            name='image',
            field=models.ImageField(null=True, upload_to=videoDownloader.models.image_upload),
        ),
        migrations.AlterField(
            model_name='downloaded',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='downloaded',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
