# Generated by Django 5.0.1 on 2024-04-02 20:46

import videoDownloader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoDownloader', '0005_alter_downloaded_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to=videoDownloader.models.image_upload)),
                ('length', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('url', models.URLField()),
                ('res', models.CharField(choices=[('highest', 'Highest Resolution'), ('720p', '720p'), ('480p', '480p'), ('360p', '360p')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Downloaded',
        ),
    ]
