# Generated by Django 5.0.1 on 2024-04-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoDownloader', '0006_audio_video_delete_downloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='res',
            field=models.CharField(max_length=10),
        ),
    ]
