# Generated by Django 5.0.1 on 2024-04-03 08:57

import videoDownloader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoDownloader', '0007_alter_video_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='audio',
            name='image',
            field=models.ImageField(upload_to=videoDownloader.models.image_upload),
        ),
        migrations.AlterField(
            model_name='audio',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
